object frmAppleMouse: TfrmAppleMouse
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = 'AppleMouse'
  ClientHeight = 209
  ClientWidth = 317
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 13
end
